#### general settings
name: none
model: base
scale: 1
peak: 8.0
gpu_ids: [1]

#### datasets
datasets:
  test:
    name: GM_ITM
    mode: LQGT_base
    dataroot_LQ: /data2/yunqiao/Synthetic_dataset/test/image
    dataroot_GT: /data2/yunqiao/Synthetic_dataset/test/gainmap
    dataroot_QM: /data2/yunqiao/Synthetic_dataset/test/metadata
    dataroot_MN: /data2/yunqiao/Synthetic_dataset/test/thumbnail
    save_img: true

#### network structures
network_G:
  which_model_G: GMNet
  in_nc: 3
  out_nc: 1
  nf: 64
  nb: 16
  act_type: relu

#### path
path:
  root: ./
  pretrain_model_G: ../checkpoints/G_synthetic.pth
  strict_load: false
